# Kubernetes Service Account linked to AWS IAM role
# Pods using this service account can call AWS Bedrock without storing credentials

apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-world-ml-sa
  namespace: default
  annotations:
    # This annotation links the K8s service account to the IAM role
    # When a pod uses this service account, it can assume the IAM role
    eks.amazonaws.com/role-arn: arn:aws:iam::942497601151:role/hello-world-ml-dev-app-role
